Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Child Project Required Docs Edit Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "32654560-f638-4e61-8aaa-382c4e812880", "8fd24692-77fb-4074-ad45-4c9ac6cbf190", "Child Project Extension")> _
Partial Public Class [ChildProjectRequiredDocsEditFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _id As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _docstatuscommunitydesccodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _docstatuscommunityphotocodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _docstatusprojectformapprovalformcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _docstatusprojectformcapitalproposalcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _docstatusprojectformcommunityformcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _docstatusprojectformintenttopartnercodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _docstatusprojectformpartneragreementcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _docstatusprojectformpartnerinfocodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _docstatusprojectformprogramcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _docstatusprojectformsponsorshipproposalfullcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _docstatusprojectformsponsorshipproposalsummarycodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _id = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _docstatuscommunitydesccodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _docstatuscommunityphotocodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _docstatusprojectformapprovalformcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _docstatusprojectformcapitalproposalcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _docstatusprojectformcommunityformcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _docstatusprojectformintenttopartnercodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _docstatusprojectformpartneragreementcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _docstatusprojectformpartnerinfocodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _docstatusprojectformprogramcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _docstatusprojectformsponsorshipproposalfullcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _docstatusprojectformsponsorshipproposalsummarycodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("32654560-f638-4e61-8aaa-382c4e812880")
        MyBase.DataFormInstanceId = New Guid("8fd24692-77fb-4074-ad45-4c9ac6cbf190")
        MyBase.RecordType = "Child Project Extension"
        MyBase.FixedDialog = True

        '
        '_id
        '
        _id.Name = "ID"
        _id.Caption = "ID"
        _id.Visible = False
        Me.Fields.Add(_id)
        '
        '_docstatuscommunitydesccodeid
        '
        _docstatuscommunitydesccodeid.Name = "DOCSTATUSCOMMUNITYDESCCODEID"
        _docstatuscommunitydesccodeid.Caption = "Community description"
        _docstatuscommunitydesccodeid.CodeTableName = "USR_CHILDPROJECTDOCUMENTATIONSTATUSCODE"
        Me.Fields.Add(_docstatuscommunitydesccodeid)
        '
        '_docstatuscommunityphotocodeid
        '
        _docstatuscommunityphotocodeid.Name = "DOCSTATUSCOMMUNITYPHOTOCODEID"
        _docstatuscommunityphotocodeid.Caption = "Community photo"
        _docstatuscommunityphotocodeid.CodeTableName = "USR_CHILDPROJECTDOCUMENTATIONSTATUSCODE"
        Me.Fields.Add(_docstatuscommunityphotocodeid)
        '
        '_docstatusprojectformapprovalformcodeid
        '
        _docstatusprojectformapprovalformcodeid.Name = "DOCSTATUSPROJECTFORMAPPROVALFORMCODEID"
        _docstatusprojectformapprovalformcodeid.Caption = "Approval form"
        _docstatusprojectformapprovalformcodeid.CodeTableName = "USR_CHILDPROJECTFORMSTATUSCODE"
        Me.Fields.Add(_docstatusprojectformapprovalformcodeid)
        '
        '_docstatusprojectformcapitalproposalcodeid
        '
        _docstatusprojectformcapitalproposalcodeid.Name = "DOCSTATUSPROJECTFORMCAPITALPROPOSALCODEID"
        _docstatusprojectformcapitalproposalcodeid.Caption = "Capital proposal"
        _docstatusprojectformcapitalproposalcodeid.CodeTableName = "USR_CHILDPROJECTFORMSTATUSCODE"
        Me.Fields.Add(_docstatusprojectformcapitalproposalcodeid)
        '
        '_docstatusprojectformcommunityformcodeid
        '
        _docstatusprojectformcommunityformcodeid.Name = "DOCSTATUSPROJECTFORMCOMMUNITYFORMCODEID"
        _docstatusprojectformcommunityformcodeid.Caption = "Community form"
        _docstatusprojectformcommunityformcodeid.CodeTableName = "USR_CHILDPROJECTFORMSTATUSCODE"
        Me.Fields.Add(_docstatusprojectformcommunityformcodeid)
        '
        '_docstatusprojectformintenttopartnercodeid
        '
        _docstatusprojectformintenttopartnercodeid.Name = "DOCSTATUSPROJECTFORMINTENTTOPARTNERCODEID"
        _docstatusprojectformintenttopartnercodeid.Caption = "Intent to partner"
        _docstatusprojectformintenttopartnercodeid.CodeTableName = "USR_CHILDPROJECTFORMSTATUSCODE"
        Me.Fields.Add(_docstatusprojectformintenttopartnercodeid)
        '
        '_docstatusprojectformpartneragreementcodeid
        '
        _docstatusprojectformpartneragreementcodeid.Name = "DOCSTATUSPROJECTFORMPARTNERAGREEMENTCODEID"
        _docstatusprojectformpartneragreementcodeid.Caption = "Partner agreement"
        _docstatusprojectformpartneragreementcodeid.CodeTableName = "USR_CHILDPROJECTFORMSTATUSCODE"
        Me.Fields.Add(_docstatusprojectformpartneragreementcodeid)
        '
        '_docstatusprojectformpartnerinfocodeid
        '
        _docstatusprojectformpartnerinfocodeid.Name = "DOCSTATUSPROJECTFORMPARTNERINFOCODEID"
        _docstatusprojectformpartnerinfocodeid.Caption = "Partner information"
        _docstatusprojectformpartnerinfocodeid.CodeTableName = "USR_CHILDPROJECTFORMSTATUSCODE"
        Me.Fields.Add(_docstatusprojectformpartnerinfocodeid)
        '
        '_docstatusprojectformprogramcodeid
        '
        _docstatusprojectformprogramcodeid.Name = "DOCSTATUSPROJECTFORMPROGRAMCODEID"
        _docstatusprojectformprogramcodeid.Caption = "Program"
        _docstatusprojectformprogramcodeid.CodeTableName = "USR_CHILDPROJECTFORMSTATUSCODE"
        Me.Fields.Add(_docstatusprojectformprogramcodeid)
        '
        '_docstatusprojectformsponsorshipproposalfullcodeid
        '
        _docstatusprojectformsponsorshipproposalfullcodeid.Name = "DOCSTATUSPROJECTFORMSPONSORSHIPPROPOSALFULLCODEID"
        _docstatusprojectformsponsorshipproposalfullcodeid.Caption = "Sponsorship proposal - full"
        _docstatusprojectformsponsorshipproposalfullcodeid.CodeTableName = "USR_CHILDPROJECTFORMSTATUSCODE"
        Me.Fields.Add(_docstatusprojectformsponsorshipproposalfullcodeid)
        '
        '_docstatusprojectformsponsorshipproposalsummarycodeid
        '
        _docstatusprojectformsponsorshipproposalsummarycodeid.Name = "DOCSTATUSPROJECTFORMSPONSORSHIPPROPOSALSUMMARYCODEID"
        _docstatusprojectformsponsorshipproposalsummarycodeid.Caption = "Sponsorship proposal - summary"
        _docstatusprojectformsponsorshipproposalsummarycodeid.CodeTableName = "USR_CHILDPROJECTFORMSTATUSCODE"
        Me.Fields.Add(_docstatusprojectformsponsorshipproposalsummarycodeid)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _id
        End Get
    End Property
    
    ''' <summary>
    ''' Community description
    ''' </summary>
    <System.ComponentModel.Description("Community description")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DOCSTATUSCOMMUNITYDESCCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _docstatuscommunitydesccodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Community photo
    ''' </summary>
    <System.ComponentModel.Description("Community photo")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DOCSTATUSCOMMUNITYPHOTOCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _docstatuscommunityphotocodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Approval form
    ''' </summary>
    <System.ComponentModel.Description("Approval form")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DOCSTATUSPROJECTFORMAPPROVALFORMCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _docstatusprojectformapprovalformcodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Capital proposal
    ''' </summary>
    <System.ComponentModel.Description("Capital proposal")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DOCSTATUSPROJECTFORMCAPITALPROPOSALCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _docstatusprojectformcapitalproposalcodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Community form
    ''' </summary>
    <System.ComponentModel.Description("Community form")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DOCSTATUSPROJECTFORMCOMMUNITYFORMCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _docstatusprojectformcommunityformcodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Intent to partner
    ''' </summary>
    <System.ComponentModel.Description("Intent to partner")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DOCSTATUSPROJECTFORMINTENTTOPARTNERCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _docstatusprojectformintenttopartnercodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Partner agreement
    ''' </summary>
    <System.ComponentModel.Description("Partner agreement")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DOCSTATUSPROJECTFORMPARTNERAGREEMENTCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _docstatusprojectformpartneragreementcodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Partner information
    ''' </summary>
    <System.ComponentModel.Description("Partner information")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DOCSTATUSPROJECTFORMPARTNERINFOCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _docstatusprojectformpartnerinfocodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Program
    ''' </summary>
    <System.ComponentModel.Description("Program")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DOCSTATUSPROJECTFORMPROGRAMCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _docstatusprojectformprogramcodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Sponsorship proposal - full
    ''' </summary>
    <System.ComponentModel.Description("Sponsorship proposal - full")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DOCSTATUSPROJECTFORMSPONSORSHIPPROPOSALFULLCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _docstatusprojectformsponsorshipproposalfullcodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Sponsorship proposal - summary
    ''' </summary>
    <System.ComponentModel.Description("Sponsorship proposal - summary")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DOCSTATUSPROJECTFORMSPONSORSHIPPROPOSALSUMMARYCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _docstatusprojectformsponsorshipproposalsummarycodeid
        End Get
    End Property
    
End Class
