Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Child Project Project Info Edit Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "04030898-13aa-45eb-b005-75fa6df3156b", "3f2f3a67-e063-4897-9002-a18458778969", "Child Project Extension")> _
Partial Public Class [ChildProjectProjectInfoEditFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _technologyavailableelectricity As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _technologyavailabletelephone As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _technologyavailablecomputer As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _technologyavailableinternet As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _maxchildrencount As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _maxgradelevelcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _maxgradelevel As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _maxchildage As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _maxchildageexceptionreason As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _monthschoolyearbeginscodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _monthschoolyearendscodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _participationagerange1lowerlimit As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _participationagerange1upperlimit As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _participationagerange1jan As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1feb As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1mar As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1apr As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1may As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1jun As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1jul As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1aug As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1sep As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1oct As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1nov As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1dec As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1sun As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1mon As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1tue As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1wed As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1thu As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1fri As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1sat As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange1hoursperweek As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _participationagerange2lowerlimit As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _participationagerange2upperlimit As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _participationagerange2jan As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2feb As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2mar As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2apr As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2may As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2jun As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2jul As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2aug As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2sep As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2oct As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2nov As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2dec As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2sun As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2mon As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2tue As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2wed As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2thu As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2fri As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2sat As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange2hoursperweek As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _participationagerange3lowerlimit As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _participationagerange3upperlimit As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _participationagerange3jan As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3feb As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3mar As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3apr As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3may As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3jun As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3jul As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3aug As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3sep As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3oct As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3nov As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3dec As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3sun As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3mon As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3tue As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3wed As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3thu As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3fri As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3sat As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange3hoursperweek As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _participationagerange4lowerlimit As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _participationagerange4upperlimit As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _participationagerange4jan As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4feb As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4mar As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4apr As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4may As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4jun As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4jul As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4aug As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4sep As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4oct As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4nov As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4dec As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4sun As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4mon As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4tue As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4wed As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4thu As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4fri As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4sat As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participationagerange4hoursperweek As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _holidaylettersduecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _letter1duecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _letter2duecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _photoupdateduecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _profileupdatecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _technologyavailableelectricity = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _technologyavailabletelephone = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _technologyavailablecomputer = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _technologyavailableinternet = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _maxchildrencount = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _maxgradelevelcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _maxgradelevel = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _maxchildage = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _maxchildageexceptionreason = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _monthschoolyearbeginscodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _monthschoolyearendscodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _participationagerange1lowerlimit = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _participationagerange1upperlimit = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _participationagerange1jan = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1feb = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1mar = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1apr = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1may = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1jun = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1jul = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1aug = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1sep = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1oct = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1nov = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1dec = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1sun = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1mon = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1tue = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1wed = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1thu = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1fri = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1sat = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange1hoursperweek = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _participationagerange2lowerlimit = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _participationagerange2upperlimit = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _participationagerange2jan = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2feb = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2mar = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2apr = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2may = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2jun = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2jul = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2aug = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2sep = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2oct = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2nov = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2dec = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2sun = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2mon = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2tue = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2wed = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2thu = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2fri = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2sat = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange2hoursperweek = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _participationagerange3lowerlimit = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _participationagerange3upperlimit = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _participationagerange3jan = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3feb = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3mar = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3apr = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3may = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3jun = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3jul = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3aug = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3sep = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3oct = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3nov = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3dec = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3sun = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3mon = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3tue = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3wed = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3thu = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3fri = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3sat = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange3hoursperweek = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _participationagerange4lowerlimit = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _participationagerange4upperlimit = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _participationagerange4jan = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4feb = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4mar = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4apr = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4may = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4jun = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4jul = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4aug = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4sep = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4oct = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4nov = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4dec = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4sun = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4mon = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4tue = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4wed = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4thu = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4fri = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4sat = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participationagerange4hoursperweek = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _holidaylettersduecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _letter1duecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _letter2duecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _photoupdateduecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _profileupdatecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("04030898-13aa-45eb-b005-75fa6df3156b")
        MyBase.DataFormInstanceId = New Guid("3f2f3a67-e063-4897-9002-a18458778969")
        MyBase.RecordType = "Child Project Extension"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildProject.ProjectInfo.EditForm.html"

        '
        '_technologyavailableelectricity
        '
        _technologyavailableelectricity.Name = "TECHNOLOGYAVAILABLEELECTRICITY"
        _technologyavailableelectricity.Caption = "Electricity"
        Me.Fields.Add(_technologyavailableelectricity)
        '
        '_technologyavailabletelephone
        '
        _technologyavailabletelephone.Name = "TECHNOLOGYAVAILABLETELEPHONE"
        _technologyavailabletelephone.Caption = "Telephone"
        Me.Fields.Add(_technologyavailabletelephone)
        '
        '_technologyavailablecomputer
        '
        _technologyavailablecomputer.Name = "TECHNOLOGYAVAILABLECOMPUTER"
        _technologyavailablecomputer.Caption = "Computer"
        Me.Fields.Add(_technologyavailablecomputer)
        '
        '_technologyavailableinternet
        '
        _technologyavailableinternet.Name = "TECHNOLOGYAVAILABLEINTERNET"
        _technologyavailableinternet.Caption = "Internet connection"
        Me.Fields.Add(_technologyavailableinternet)
        '
        '_maxchildrencount
        '
        _maxchildrencount.Name = "MAXCHILDRENCOUNT"
        _maxchildrencount.Caption = "Maximum number of children"
        Me.Fields.Add(_maxchildrencount)
        '
        '_maxgradelevelcodeid
        '
        _maxgradelevelcodeid.Name = "MAXGRADELEVELCODEID"
        _maxgradelevelcodeid.Caption = "Maximum grade level"
        _maxgradelevelcodeid.CodeTableName = "USR_CHILDPROJECTMAXGRADELEVELCODE"
        Me.Fields.Add(_maxgradelevelcodeid)
        '
        '_maxgradelevel
        '
        _maxgradelevel.Name = "MAXGRADELEVEL"
        _maxgradelevel.Caption = "Grade level"
        _maxgradelevel.MaxLength = 10
        Me.Fields.Add(_maxgradelevel)
        '
        '_maxchildage
        '
        _maxchildage.Name = "MAXCHILDAGE"
        _maxchildage.Caption = "Maximum child age"
        Me.Fields.Add(_maxchildage)
        '
        '_maxchildageexceptionreason
        '
        _maxchildageexceptionreason.Name = "MAXCHILDAGEEXCEPTIONREASON"
        _maxchildageexceptionreason.Caption = "If not 18, explain"
        _maxchildageexceptionreason.MaxLength = 100
        Me.Fields.Add(_maxchildageexceptionreason)
        '
        '_monthschoolyearbeginscodeid
        '
        _monthschoolyearbeginscodeid.Name = "MONTHSCHOOLYEARBEGINSCODEID"
        _monthschoolyearbeginscodeid.Caption = "Month school year begins"
        _monthschoolyearbeginscodeid.CodeTableName = "USR_MONTHCODE"
        Me.Fields.Add(_monthschoolyearbeginscodeid)
        '
        '_monthschoolyearendscodeid
        '
        _monthschoolyearendscodeid.Name = "MONTHSCHOOLYEARENDSCODEID"
        _monthschoolyearendscodeid.Caption = "Month school year ends"
        _monthschoolyearendscodeid.CodeTableName = "USR_MONTHCODE"
        Me.Fields.Add(_monthschoolyearendscodeid)
        '
        '_participationagerange1lowerlimit
        '
        _participationagerange1lowerlimit.Name = "PARTICIPATIONAGERANGE1LOWERLIMIT"
        _participationagerange1lowerlimit.Caption = "Participationagerange1lowerlimit"
        Me.Fields.Add(_participationagerange1lowerlimit)
        '
        '_participationagerange1upperlimit
        '
        _participationagerange1upperlimit.Name = "PARTICIPATIONAGERANGE1UPPERLIMIT"
        _participationagerange1upperlimit.Caption = "Participationagerange1upperlimit"
        Me.Fields.Add(_participationagerange1upperlimit)
        '
        '_participationagerange1jan
        '
        _participationagerange1jan.Name = "PARTICIPATIONAGERANGE1JAN"
        _participationagerange1jan.Caption = "Participationagerange1jan"
        Me.Fields.Add(_participationagerange1jan)
        '
        '_participationagerange1feb
        '
        _participationagerange1feb.Name = "PARTICIPATIONAGERANGE1FEB"
        _participationagerange1feb.Caption = "Participationagerange1feb"
        Me.Fields.Add(_participationagerange1feb)
        '
        '_participationagerange1mar
        '
        _participationagerange1mar.Name = "PARTICIPATIONAGERANGE1MAR"
        _participationagerange1mar.Caption = "Participationagerange1mar"
        Me.Fields.Add(_participationagerange1mar)
        '
        '_participationagerange1apr
        '
        _participationagerange1apr.Name = "PARTICIPATIONAGERANGE1APR"
        _participationagerange1apr.Caption = "Participationagerange1apr"
        Me.Fields.Add(_participationagerange1apr)
        '
        '_participationagerange1may
        '
        _participationagerange1may.Name = "PARTICIPATIONAGERANGE1MAY"
        _participationagerange1may.Caption = "Participationagerange1may"
        Me.Fields.Add(_participationagerange1may)
        '
        '_participationagerange1jun
        '
        _participationagerange1jun.Name = "PARTICIPATIONAGERANGE1JUN"
        _participationagerange1jun.Caption = "Participationagerange1jun"
        Me.Fields.Add(_participationagerange1jun)
        '
        '_participationagerange1jul
        '
        _participationagerange1jul.Name = "PARTICIPATIONAGERANGE1JUL"
        _participationagerange1jul.Caption = "Participationagerange1jul"
        Me.Fields.Add(_participationagerange1jul)
        '
        '_participationagerange1aug
        '
        _participationagerange1aug.Name = "PARTICIPATIONAGERANGE1AUG"
        _participationagerange1aug.Caption = "Participationagerange1aug"
        Me.Fields.Add(_participationagerange1aug)
        '
        '_participationagerange1sep
        '
        _participationagerange1sep.Name = "PARTICIPATIONAGERANGE1SEP"
        _participationagerange1sep.Caption = "Participationagerange1sep"
        Me.Fields.Add(_participationagerange1sep)
        '
        '_participationagerange1oct
        '
        _participationagerange1oct.Name = "PARTICIPATIONAGERANGE1OCT"
        _participationagerange1oct.Caption = "Participationagerange1oct"
        Me.Fields.Add(_participationagerange1oct)
        '
        '_participationagerange1nov
        '
        _participationagerange1nov.Name = "PARTICIPATIONAGERANGE1NOV"
        _participationagerange1nov.Caption = "Participationagerange1nov"
        Me.Fields.Add(_participationagerange1nov)
        '
        '_participationagerange1dec
        '
        _participationagerange1dec.Name = "PARTICIPATIONAGERANGE1DEC"
        _participationagerange1dec.Caption = "Participationagerange1dec"
        Me.Fields.Add(_participationagerange1dec)
        '
        '_participationagerange1sun
        '
        _participationagerange1sun.Name = "PARTICIPATIONAGERANGE1SUN"
        _participationagerange1sun.Caption = "Participationagerange1sun"
        Me.Fields.Add(_participationagerange1sun)
        '
        '_participationagerange1mon
        '
        _participationagerange1mon.Name = "PARTICIPATIONAGERANGE1MON"
        _participationagerange1mon.Caption = "Participationagerange1mon"
        Me.Fields.Add(_participationagerange1mon)
        '
        '_participationagerange1tue
        '
        _participationagerange1tue.Name = "PARTICIPATIONAGERANGE1TUE"
        _participationagerange1tue.Caption = "Participationagerange1tue"
        Me.Fields.Add(_participationagerange1tue)
        '
        '_participationagerange1wed
        '
        _participationagerange1wed.Name = "PARTICIPATIONAGERANGE1WED"
        _participationagerange1wed.Caption = "Participationagerange1wed"
        Me.Fields.Add(_participationagerange1wed)
        '
        '_participationagerange1thu
        '
        _participationagerange1thu.Name = "PARTICIPATIONAGERANGE1THU"
        _participationagerange1thu.Caption = "Participationagerange1thu"
        Me.Fields.Add(_participationagerange1thu)
        '
        '_participationagerange1fri
        '
        _participationagerange1fri.Name = "PARTICIPATIONAGERANGE1FRI"
        _participationagerange1fri.Caption = "Participationagerange1fri"
        Me.Fields.Add(_participationagerange1fri)
        '
        '_participationagerange1sat
        '
        _participationagerange1sat.Name = "PARTICIPATIONAGERANGE1SAT"
        _participationagerange1sat.Caption = "Participationagerange1sat"
        Me.Fields.Add(_participationagerange1sat)
        '
        '_participationagerange1hoursperweek
        '
        _participationagerange1hoursperweek.Name = "PARTICIPATIONAGERANGE1HOURSPERWEEK"
        _participationagerange1hoursperweek.Caption = "Participationagerange1hoursperweek"
        Me.Fields.Add(_participationagerange1hoursperweek)
        '
        '_participationagerange2lowerlimit
        '
        _participationagerange2lowerlimit.Name = "PARTICIPATIONAGERANGE2LOWERLIMIT"
        _participationagerange2lowerlimit.Caption = "Participationagerange2lowerlimit"
        Me.Fields.Add(_participationagerange2lowerlimit)
        '
        '_participationagerange2upperlimit
        '
        _participationagerange2upperlimit.Name = "PARTICIPATIONAGERANGE2UPPERLIMIT"
        _participationagerange2upperlimit.Caption = "Participationagerange2upperlimit"
        Me.Fields.Add(_participationagerange2upperlimit)
        '
        '_participationagerange2jan
        '
        _participationagerange2jan.Name = "PARTICIPATIONAGERANGE2JAN"
        _participationagerange2jan.Caption = "Participationagerange2jan"
        Me.Fields.Add(_participationagerange2jan)
        '
        '_participationagerange2feb
        '
        _participationagerange2feb.Name = "PARTICIPATIONAGERANGE2FEB"
        _participationagerange2feb.Caption = "Participationagerange2feb"
        Me.Fields.Add(_participationagerange2feb)
        '
        '_participationagerange2mar
        '
        _participationagerange2mar.Name = "PARTICIPATIONAGERANGE2MAR"
        _participationagerange2mar.Caption = "Participationagerange2mar"
        Me.Fields.Add(_participationagerange2mar)
        '
        '_participationagerange2apr
        '
        _participationagerange2apr.Name = "PARTICIPATIONAGERANGE2APR"
        _participationagerange2apr.Caption = "Participationagerange2apr"
        Me.Fields.Add(_participationagerange2apr)
        '
        '_participationagerange2may
        '
        _participationagerange2may.Name = "PARTICIPATIONAGERANGE2MAY"
        _participationagerange2may.Caption = "Participationagerange2may"
        Me.Fields.Add(_participationagerange2may)
        '
        '_participationagerange2jun
        '
        _participationagerange2jun.Name = "PARTICIPATIONAGERANGE2JUN"
        _participationagerange2jun.Caption = "Participationagerange2jun"
        Me.Fields.Add(_participationagerange2jun)
        '
        '_participationagerange2jul
        '
        _participationagerange2jul.Name = "PARTICIPATIONAGERANGE2JUL"
        _participationagerange2jul.Caption = "Participationagerange2jul"
        Me.Fields.Add(_participationagerange2jul)
        '
        '_participationagerange2aug
        '
        _participationagerange2aug.Name = "PARTICIPATIONAGERANGE2AUG"
        _participationagerange2aug.Caption = "Participationagerange2aug"
        Me.Fields.Add(_participationagerange2aug)
        '
        '_participationagerange2sep
        '
        _participationagerange2sep.Name = "PARTICIPATIONAGERANGE2SEP"
        _participationagerange2sep.Caption = "Participationagerange2sep"
        Me.Fields.Add(_participationagerange2sep)
        '
        '_participationagerange2oct
        '
        _participationagerange2oct.Name = "PARTICIPATIONAGERANGE2OCT"
        _participationagerange2oct.Caption = "Participationagerange2oct"
        Me.Fields.Add(_participationagerange2oct)
        '
        '_participationagerange2nov
        '
        _participationagerange2nov.Name = "PARTICIPATIONAGERANGE2NOV"
        _participationagerange2nov.Caption = "Participationagerange2nov"
        Me.Fields.Add(_participationagerange2nov)
        '
        '_participationagerange2dec
        '
        _participationagerange2dec.Name = "PARTICIPATIONAGERANGE2DEC"
        _participationagerange2dec.Caption = "Participationagerange2dec"
        Me.Fields.Add(_participationagerange2dec)
        '
        '_participationagerange2sun
        '
        _participationagerange2sun.Name = "PARTICIPATIONAGERANGE2SUN"
        _participationagerange2sun.Caption = "Participationagerange2sun"
        Me.Fields.Add(_participationagerange2sun)
        '
        '_participationagerange2mon
        '
        _participationagerange2mon.Name = "PARTICIPATIONAGERANGE2MON"
        _participationagerange2mon.Caption = "Participationagerange2mon"
        Me.Fields.Add(_participationagerange2mon)
        '
        '_participationagerange2tue
        '
        _participationagerange2tue.Name = "PARTICIPATIONAGERANGE2TUE"
        _participationagerange2tue.Caption = "Participationagerange2tue"
        Me.Fields.Add(_participationagerange2tue)
        '
        '_participationagerange2wed
        '
        _participationagerange2wed.Name = "PARTICIPATIONAGERANGE2WED"
        _participationagerange2wed.Caption = "Participationagerange2wed"
        Me.Fields.Add(_participationagerange2wed)
        '
        '_participationagerange2thu
        '
        _participationagerange2thu.Name = "PARTICIPATIONAGERANGE2THU"
        _participationagerange2thu.Caption = "Participationagerange2thu"
        Me.Fields.Add(_participationagerange2thu)
        '
        '_participationagerange2fri
        '
        _participationagerange2fri.Name = "PARTICIPATIONAGERANGE2FRI"
        _participationagerange2fri.Caption = "Participationagerange2fri"
        Me.Fields.Add(_participationagerange2fri)
        '
        '_participationagerange2sat
        '
        _participationagerange2sat.Name = "PARTICIPATIONAGERANGE2SAT"
        _participationagerange2sat.Caption = "Participationagerange2sat"
        Me.Fields.Add(_participationagerange2sat)
        '
        '_participationagerange2hoursperweek
        '
        _participationagerange2hoursperweek.Name = "PARTICIPATIONAGERANGE2HOURSPERWEEK"
        _participationagerange2hoursperweek.Caption = "Participationagerange2hoursperweek"
        Me.Fields.Add(_participationagerange2hoursperweek)
        '
        '_participationagerange3lowerlimit
        '
        _participationagerange3lowerlimit.Name = "PARTICIPATIONAGERANGE3LOWERLIMIT"
        _participationagerange3lowerlimit.Caption = "Participationagerange3lowerlimit"
        Me.Fields.Add(_participationagerange3lowerlimit)
        '
        '_participationagerange3upperlimit
        '
        _participationagerange3upperlimit.Name = "PARTICIPATIONAGERANGE3UPPERLIMIT"
        _participationagerange3upperlimit.Caption = "Participationagerange3upperlimit"
        Me.Fields.Add(_participationagerange3upperlimit)
        '
        '_participationagerange3jan
        '
        _participationagerange3jan.Name = "PARTICIPATIONAGERANGE3JAN"
        _participationagerange3jan.Caption = "Participationagerange3jan"
        Me.Fields.Add(_participationagerange3jan)
        '
        '_participationagerange3feb
        '
        _participationagerange3feb.Name = "PARTICIPATIONAGERANGE3FEB"
        _participationagerange3feb.Caption = "Participationagerange3feb"
        Me.Fields.Add(_participationagerange3feb)
        '
        '_participationagerange3mar
        '
        _participationagerange3mar.Name = "PARTICIPATIONAGERANGE3MAR"
        _participationagerange3mar.Caption = "Participationagerange3mar"
        Me.Fields.Add(_participationagerange3mar)
        '
        '_participationagerange3apr
        '
        _participationagerange3apr.Name = "PARTICIPATIONAGERANGE3APR"
        _participationagerange3apr.Caption = "Participationagerange3apr"
        Me.Fields.Add(_participationagerange3apr)
        '
        '_participationagerange3may
        '
        _participationagerange3may.Name = "PARTICIPATIONAGERANGE3MAY"
        _participationagerange3may.Caption = "Participationagerange3may"
        Me.Fields.Add(_participationagerange3may)
        '
        '_participationagerange3jun
        '
        _participationagerange3jun.Name = "PARTICIPATIONAGERANGE3JUN"
        _participationagerange3jun.Caption = "Participationagerange3jun"
        Me.Fields.Add(_participationagerange3jun)
        '
        '_participationagerange3jul
        '
        _participationagerange3jul.Name = "PARTICIPATIONAGERANGE3JUL"
        _participationagerange3jul.Caption = "Participationagerange3jul"
        Me.Fields.Add(_participationagerange3jul)
        '
        '_participationagerange3aug
        '
        _participationagerange3aug.Name = "PARTICIPATIONAGERANGE3AUG"
        _participationagerange3aug.Caption = "Participationagerange3aug"
        Me.Fields.Add(_participationagerange3aug)
        '
        '_participationagerange3sep
        '
        _participationagerange3sep.Name = "PARTICIPATIONAGERANGE3SEP"
        _participationagerange3sep.Caption = "Participationagerange3sep"
        Me.Fields.Add(_participationagerange3sep)
        '
        '_participationagerange3oct
        '
        _participationagerange3oct.Name = "PARTICIPATIONAGERANGE3OCT"
        _participationagerange3oct.Caption = "Participationagerange3oct"
        Me.Fields.Add(_participationagerange3oct)
        '
        '_participationagerange3nov
        '
        _participationagerange3nov.Name = "PARTICIPATIONAGERANGE3NOV"
        _participationagerange3nov.Caption = "Participationagerange3nov"
        Me.Fields.Add(_participationagerange3nov)
        '
        '_participationagerange3dec
        '
        _participationagerange3dec.Name = "PARTICIPATIONAGERANGE3DEC"
        _participationagerange3dec.Caption = "Participationagerange3dec"
        Me.Fields.Add(_participationagerange3dec)
        '
        '_participationagerange3sun
        '
        _participationagerange3sun.Name = "PARTICIPATIONAGERANGE3SUN"
        _participationagerange3sun.Caption = "Participationagerange3sun"
        Me.Fields.Add(_participationagerange3sun)
        '
        '_participationagerange3mon
        '
        _participationagerange3mon.Name = "PARTICIPATIONAGERANGE3MON"
        _participationagerange3mon.Caption = "Participationagerange3mon"
        Me.Fields.Add(_participationagerange3mon)
        '
        '_participationagerange3tue
        '
        _participationagerange3tue.Name = "PARTICIPATIONAGERANGE3TUE"
        _participationagerange3tue.Caption = "Participationagerange3tue"
        Me.Fields.Add(_participationagerange3tue)
        '
        '_participationagerange3wed
        '
        _participationagerange3wed.Name = "PARTICIPATIONAGERANGE3WED"
        _participationagerange3wed.Caption = "Participationagerange3wed"
        Me.Fields.Add(_participationagerange3wed)
        '
        '_participationagerange3thu
        '
        _participationagerange3thu.Name = "PARTICIPATIONAGERANGE3THU"
        _participationagerange3thu.Caption = "Participationagerange3thu"
        Me.Fields.Add(_participationagerange3thu)
        '
        '_participationagerange3fri
        '
        _participationagerange3fri.Name = "PARTICIPATIONAGERANGE3FRI"
        _participationagerange3fri.Caption = "Participationagerange3fri"
        Me.Fields.Add(_participationagerange3fri)
        '
        '_participationagerange3sat
        '
        _participationagerange3sat.Name = "PARTICIPATIONAGERANGE3SAT"
        _participationagerange3sat.Caption = "Participationagerange3sat"
        Me.Fields.Add(_participationagerange3sat)
        '
        '_participationagerange3hoursperweek
        '
        _participationagerange3hoursperweek.Name = "PARTICIPATIONAGERANGE3HOURSPERWEEK"
        _participationagerange3hoursperweek.Caption = "Participationagerange3hoursperweek"
        Me.Fields.Add(_participationagerange3hoursperweek)
        '
        '_participationagerange4lowerlimit
        '
        _participationagerange4lowerlimit.Name = "PARTICIPATIONAGERANGE4LOWERLIMIT"
        _participationagerange4lowerlimit.Caption = "Participationagerange4lowerlimit"
        Me.Fields.Add(_participationagerange4lowerlimit)
        '
        '_participationagerange4upperlimit
        '
        _participationagerange4upperlimit.Name = "PARTICIPATIONAGERANGE4UPPERLIMIT"
        _participationagerange4upperlimit.Caption = "Participationagerange4upperlimit"
        Me.Fields.Add(_participationagerange4upperlimit)
        '
        '_participationagerange4jan
        '
        _participationagerange4jan.Name = "PARTICIPATIONAGERANGE4JAN"
        _participationagerange4jan.Caption = "Participationagerange4jan"
        Me.Fields.Add(_participationagerange4jan)
        '
        '_participationagerange4feb
        '
        _participationagerange4feb.Name = "PARTICIPATIONAGERANGE4FEB"
        _participationagerange4feb.Caption = "Participationagerange4feb"
        Me.Fields.Add(_participationagerange4feb)
        '
        '_participationagerange4mar
        '
        _participationagerange4mar.Name = "PARTICIPATIONAGERANGE4MAR"
        _participationagerange4mar.Caption = "Participationagerange4mar"
        Me.Fields.Add(_participationagerange4mar)
        '
        '_participationagerange4apr
        '
        _participationagerange4apr.Name = "PARTICIPATIONAGERANGE4APR"
        _participationagerange4apr.Caption = "Participationagerange4apr"
        Me.Fields.Add(_participationagerange4apr)
        '
        '_participationagerange4may
        '
        _participationagerange4may.Name = "PARTICIPATIONAGERANGE4MAY"
        _participationagerange4may.Caption = "Participationagerange4may"
        Me.Fields.Add(_participationagerange4may)
        '
        '_participationagerange4jun
        '
        _participationagerange4jun.Name = "PARTICIPATIONAGERANGE4JUN"
        _participationagerange4jun.Caption = "Participationagerange4jun"
        Me.Fields.Add(_participationagerange4jun)
        '
        '_participationagerange4jul
        '
        _participationagerange4jul.Name = "PARTICIPATIONAGERANGE4JUL"
        _participationagerange4jul.Caption = "Participationagerange4jul"
        Me.Fields.Add(_participationagerange4jul)
        '
        '_participationagerange4aug
        '
        _participationagerange4aug.Name = "PARTICIPATIONAGERANGE4AUG"
        _participationagerange4aug.Caption = "Participationagerange4aug"
        Me.Fields.Add(_participationagerange4aug)
        '
        '_participationagerange4sep
        '
        _participationagerange4sep.Name = "PARTICIPATIONAGERANGE4SEP"
        _participationagerange4sep.Caption = "Participationagerange4sep"
        Me.Fields.Add(_participationagerange4sep)
        '
        '_participationagerange4oct
        '
        _participationagerange4oct.Name = "PARTICIPATIONAGERANGE4OCT"
        _participationagerange4oct.Caption = "Participationagerange4oct"
        Me.Fields.Add(_participationagerange4oct)
        '
        '_participationagerange4nov
        '
        _participationagerange4nov.Name = "PARTICIPATIONAGERANGE4NOV"
        _participationagerange4nov.Caption = "Participationagerange4nov"
        Me.Fields.Add(_participationagerange4nov)
        '
        '_participationagerange4dec
        '
        _participationagerange4dec.Name = "PARTICIPATIONAGERANGE4DEC"
        _participationagerange4dec.Caption = "Participationagerange4dec"
        Me.Fields.Add(_participationagerange4dec)
        '
        '_participationagerange4sun
        '
        _participationagerange4sun.Name = "PARTICIPATIONAGERANGE4SUN"
        _participationagerange4sun.Caption = "Participationagerange4sun"
        Me.Fields.Add(_participationagerange4sun)
        '
        '_participationagerange4mon
        '
        _participationagerange4mon.Name = "PARTICIPATIONAGERANGE4MON"
        _participationagerange4mon.Caption = "Participationagerange4mon"
        Me.Fields.Add(_participationagerange4mon)
        '
        '_participationagerange4tue
        '
        _participationagerange4tue.Name = "PARTICIPATIONAGERANGE4TUE"
        _participationagerange4tue.Caption = "Participationagerange4tue"
        Me.Fields.Add(_participationagerange4tue)
        '
        '_participationagerange4wed
        '
        _participationagerange4wed.Name = "PARTICIPATIONAGERANGE4WED"
        _participationagerange4wed.Caption = "Participationagerange4wed"
        Me.Fields.Add(_participationagerange4wed)
        '
        '_participationagerange4thu
        '
        _participationagerange4thu.Name = "PARTICIPATIONAGERANGE4THU"
        _participationagerange4thu.Caption = "Participationagerange4thu"
        Me.Fields.Add(_participationagerange4thu)
        '
        '_participationagerange4fri
        '
        _participationagerange4fri.Name = "PARTICIPATIONAGERANGE4FRI"
        _participationagerange4fri.Caption = "Participationagerange4fri"
        Me.Fields.Add(_participationagerange4fri)
        '
        '_participationagerange4sat
        '
        _participationagerange4sat.Name = "PARTICIPATIONAGERANGE4SAT"
        _participationagerange4sat.Caption = "Participationagerange4sat"
        Me.Fields.Add(_participationagerange4sat)
        '
        '_participationagerange4hoursperweek
        '
        _participationagerange4hoursperweek.Name = "PARTICIPATIONAGERANGE4HOURSPERWEEK"
        _participationagerange4hoursperweek.Caption = "Participationagerange4hoursperweek"
        Me.Fields.Add(_participationagerange4hoursperweek)
        '
        '_holidaylettersduecodeid
        '
        _holidaylettersduecodeid.Name = "HOLIDAYLETTERSDUECODEID"
        _holidaylettersduecodeid.Caption = "Holiday letters due"
        _holidaylettersduecodeid.CodeTableName = "USR_MONTHCODE"
        Me.Fields.Add(_holidaylettersduecodeid)
        '
        '_letter1duecodeid
        '
        _letter1duecodeid.Name = "LETTER1DUECODEID"
        _letter1duecodeid.Caption = "Letter 1 due"
        _letter1duecodeid.CodeTableName = "USR_MONTHCODE"
        Me.Fields.Add(_letter1duecodeid)
        '
        '_letter2duecodeid
        '
        _letter2duecodeid.Name = "LETTER2DUECODEID"
        _letter2duecodeid.Caption = "Letter 2 due"
        _letter2duecodeid.CodeTableName = "USR_MONTHCODE"
        Me.Fields.Add(_letter2duecodeid)
        '
        '_photoupdateduecodeid
        '
        _photoupdateduecodeid.Name = "PHOTOUPDATEDUECODEID"
        _photoupdateduecodeid.Caption = "Photo update due"
        _photoupdateduecodeid.CodeTableName = "USR_MONTHCODE"
        Me.Fields.Add(_photoupdateduecodeid)
        '
        '_profileupdatecodeid
        '
        _profileupdatecodeid.Name = "PROFILEUPDATECODEID"
        _profileupdatecodeid.Caption = "Profile update"
        _profileupdatecodeid.CodeTableName = "USR_MONTHCODE"
        Me.Fields.Add(_profileupdatecodeid)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Electricity
    ''' </summary>
    <System.ComponentModel.Description("Electricity")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [TECHNOLOGYAVAILABLEELECTRICITY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _technologyavailableelectricity
        End Get
    End Property
    
    ''' <summary>
    ''' Telephone
    ''' </summary>
    <System.ComponentModel.Description("Telephone")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [TECHNOLOGYAVAILABLETELEPHONE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _technologyavailabletelephone
        End Get
    End Property
    
    ''' <summary>
    ''' Computer
    ''' </summary>
    <System.ComponentModel.Description("Computer")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [TECHNOLOGYAVAILABLECOMPUTER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _technologyavailablecomputer
        End Get
    End Property
    
    ''' <summary>
    ''' Internet connection
    ''' </summary>
    <System.ComponentModel.Description("Internet connection")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [TECHNOLOGYAVAILABLEINTERNET]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _technologyavailableinternet
        End Get
    End Property
    
    ''' <summary>
    ''' Maximum number of children
    ''' </summary>
    <System.ComponentModel.Description("Maximum number of children")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MAXCHILDRENCOUNT]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _maxchildrencount
        End Get
    End Property
    
    ''' <summary>
    ''' Maximum grade level
    ''' </summary>
    <System.ComponentModel.Description("Maximum grade level")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MAXGRADELEVELCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _maxgradelevelcodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Grade level
    ''' </summary>
    <System.ComponentModel.Description("Grade level")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MAXGRADELEVEL]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _maxgradelevel
        End Get
    End Property
    
    ''' <summary>
    ''' Maximum child age
    ''' </summary>
    <System.ComponentModel.Description("Maximum child age")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MAXCHILDAGE]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _maxchildage
        End Get
    End Property
    
    ''' <summary>
    ''' If not 18, explain
    ''' </summary>
    <System.ComponentModel.Description("If not 18, explain")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MAXCHILDAGEEXCEPTIONREASON]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _maxchildageexceptionreason
        End Get
    End Property
    
    ''' <summary>
    ''' Month school year begins
    ''' </summary>
    <System.ComponentModel.Description("Month school year begins")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MONTHSCHOOLYEARBEGINSCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _monthschoolyearbeginscodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Month school year ends
    ''' </summary>
    <System.ComponentModel.Description("Month school year ends")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MONTHSCHOOLYEARENDSCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _monthschoolyearendscodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1lowerlimit
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1lowerlimit")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1LOWERLIMIT]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _participationagerange1lowerlimit
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1upperlimit
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1upperlimit")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1UPPERLIMIT]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _participationagerange1upperlimit
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1jan
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1jan")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1JAN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1jan
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1feb
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1feb")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1FEB]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1feb
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1mar
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1mar")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1MAR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1mar
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1apr
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1apr")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1APR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1apr
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1may
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1may")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1MAY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1may
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1jun
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1jun")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1JUN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1jun
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1jul
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1jul")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1JUL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1jul
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1aug
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1aug")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1AUG]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1aug
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1sep
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1sep")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1SEP]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1sep
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1oct
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1oct")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1OCT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1oct
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1nov
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1nov")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1NOV]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1nov
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1dec
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1dec")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1DEC]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1dec
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1sun
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1sun")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1SUN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1sun
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1mon
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1mon")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1MON]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1mon
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1tue
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1tue")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1TUE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1tue
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1wed
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1wed")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1WED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1wed
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1thu
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1thu")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1THU]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1thu
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1fri
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1fri")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1FRI]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1fri
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1sat
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1sat")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1SAT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange1sat
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange1hoursperweek
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange1hoursperweek")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE1HOURSPERWEEK]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _participationagerange1hoursperweek
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2lowerlimit
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2lowerlimit")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2LOWERLIMIT]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _participationagerange2lowerlimit
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2upperlimit
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2upperlimit")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2UPPERLIMIT]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _participationagerange2upperlimit
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2jan
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2jan")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2JAN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2jan
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2feb
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2feb")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2FEB]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2feb
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2mar
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2mar")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2MAR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2mar
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2apr
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2apr")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2APR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2apr
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2may
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2may")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2MAY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2may
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2jun
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2jun")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2JUN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2jun
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2jul
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2jul")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2JUL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2jul
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2aug
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2aug")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2AUG]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2aug
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2sep
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2sep")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2SEP]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2sep
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2oct
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2oct")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2OCT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2oct
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2nov
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2nov")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2NOV]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2nov
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2dec
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2dec")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2DEC]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2dec
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2sun
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2sun")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2SUN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2sun
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2mon
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2mon")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2MON]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2mon
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2tue
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2tue")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2TUE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2tue
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2wed
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2wed")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2WED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2wed
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2thu
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2thu")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2THU]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2thu
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2fri
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2fri")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2FRI]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2fri
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2sat
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2sat")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2SAT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange2sat
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange2hoursperweek
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange2hoursperweek")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE2HOURSPERWEEK]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _participationagerange2hoursperweek
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3lowerlimit
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3lowerlimit")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3LOWERLIMIT]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _participationagerange3lowerlimit
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3upperlimit
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3upperlimit")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3UPPERLIMIT]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _participationagerange3upperlimit
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3jan
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3jan")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3JAN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3jan
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3feb
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3feb")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3FEB]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3feb
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3mar
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3mar")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3MAR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3mar
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3apr
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3apr")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3APR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3apr
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3may
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3may")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3MAY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3may
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3jun
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3jun")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3JUN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3jun
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3jul
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3jul")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3JUL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3jul
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3aug
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3aug")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3AUG]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3aug
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3sep
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3sep")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3SEP]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3sep
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3oct
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3oct")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3OCT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3oct
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3nov
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3nov")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3NOV]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3nov
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3dec
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3dec")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3DEC]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3dec
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3sun
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3sun")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3SUN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3sun
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3mon
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3mon")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3MON]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3mon
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3tue
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3tue")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3TUE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3tue
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3wed
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3wed")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3WED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3wed
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3thu
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3thu")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3THU]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3thu
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3fri
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3fri")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3FRI]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3fri
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3sat
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3sat")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3SAT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange3sat
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange3hoursperweek
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange3hoursperweek")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE3HOURSPERWEEK]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _participationagerange3hoursperweek
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4lowerlimit
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4lowerlimit")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4LOWERLIMIT]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _participationagerange4lowerlimit
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4upperlimit
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4upperlimit")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4UPPERLIMIT]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _participationagerange4upperlimit
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4jan
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4jan")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4JAN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4jan
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4feb
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4feb")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4FEB]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4feb
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4mar
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4mar")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4MAR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4mar
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4apr
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4apr")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4APR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4apr
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4may
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4may")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4MAY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4may
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4jun
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4jun")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4JUN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4jun
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4jul
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4jul")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4JUL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4jul
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4aug
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4aug")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4AUG]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4aug
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4sep
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4sep")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4SEP]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4sep
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4oct
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4oct")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4OCT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4oct
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4nov
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4nov")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4NOV]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4nov
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4dec
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4dec")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4DEC]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4dec
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4sun
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4sun")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4SUN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4sun
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4mon
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4mon")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4MON]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4mon
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4tue
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4tue")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4TUE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4tue
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4wed
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4wed")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4WED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4wed
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4thu
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4thu")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4THU]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4thu
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4fri
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4fri")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4FRI]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4fri
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4sat
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4sat")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4SAT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participationagerange4sat
        End Get
    End Property
    
    ''' <summary>
    ''' Participationagerange4hoursperweek
    ''' </summary>
    <System.ComponentModel.Description("Participationagerange4hoursperweek")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PARTICIPATIONAGERANGE4HOURSPERWEEK]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _participationagerange4hoursperweek
        End Get
    End Property
    
    ''' <summary>
    ''' Holiday letters due
    ''' </summary>
    <System.ComponentModel.Description("Holiday letters due")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [HOLIDAYLETTERSDUECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _holidaylettersduecodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Letter 1 due
    ''' </summary>
    <System.ComponentModel.Description("Letter 1 due")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [LETTER1DUECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _letter1duecodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Letter 2 due
    ''' </summary>
    <System.ComponentModel.Description("Letter 2 due")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [LETTER2DUECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _letter2duecodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Photo update due
    ''' </summary>
    <System.ComponentModel.Description("Photo update due")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PHOTOUPDATEDUECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _photoupdateduecodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Profile update
    ''' </summary>
    <System.ComponentModel.Description("Profile update")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PROFILEUPDATECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _profileupdatecodeid
        End Get
    End Property
    
End Class
