Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Child Project Community 2 View Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "27a61e8a-fe9b-4c12-be67-9c8fdc0e9e04", "5d8256e5-bbc9-4b3d-8b23-123b4c4bfe44", "Child Project Extension")> _
Partial Public Class [ChildProjectCommunity2ViewFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _id As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _highesteducationavailablecode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _highesteducationavailablecodeid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _highesteducationavailableother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _educationsystemdivisions As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _educationtypepublic As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _educationtypeprivate As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _educationtypereligious As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _educationtypeother As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _educationtypeotherdesc As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _vocationaltrainingavailable As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _percentchildrennotinschool As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _percentchildrencompletedprimaryschool As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _percentyouthcompletedsecondaryschool As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _avgfamilymonthlyincome As Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
    Private WithEvents _avgfamilymonthlyincomeinusdollars As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _primaryoccupationherding As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _primaryoccupationdaylabor As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _primaryoccupationdomestic As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _primaryoccupationfactory As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _primaryoccupationfishing As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _primaryoccupationgovernment As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _primaryoccupationstreetvending As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _primaryoccupationfarming As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _primaryoccupationtrading As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _primaryoccupationplantation As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _primaryoccupationporter As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _primaryoccupationother As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _primaryoccupationotherdesc As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _avghoursperweek As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _unemploymentrate As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _localtraditions As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _holidays As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _primaryethnicgroups As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _primarylanguages As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _familystructurepartriarchal As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _familystructurematriarchal As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _familystructurefamilydisintegration As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _familystructuresingleparent As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _familystructureextendedfamily As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _familystructurechildheaded As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _familystructureother As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _familystructureotherdesc As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _socialissuesalcoholabuse As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissueschildabuse As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissueschildlabor As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissueschildprostitution As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissueschildtrafficking As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissueschildheadedhouseholds As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissuesdrugabuse As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissuesforcedmarriage As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissuesgirlchilddiscrimination As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissueshighdivorce As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissuesorphans As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissuesrefugees As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissuessingleparentfamilies As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissuestrauma As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissueswar As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissuesother As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _socialissuesotherdesc As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _legalprotectionnotaware As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _legalprotectionawarenotenforced As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _legalprotectionawareenforced As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _childlaborregularlyinlaborpool As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _childlaborrsometimesinlaborpool As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _childlabornotinlaborpool As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _childcarewhenparentabsentadoption As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _childcarewhenparentabsentextendedfamily As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _childcarewhenparentabsentfostercare As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _childcarewhenparentabsentinstitution As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _childcarewhenparentabsentnocare As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _childcarewhenparentabsentother As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _childcarewhenparentabsentotherdesc As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _localadoptionaccepted As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _foreignadoptionlegal As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _highesteducationavailableotherseparator As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _educationtypeotherseparator As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _primaryoccupationotherseparator As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _familystructureotherseparator As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _socialissuesotherseparator As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _id = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _highesteducationavailablecode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _highesteducationavailablecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _highesteducationavailableother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _educationsystemdivisions = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _educationtypepublic = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _educationtypeprivate = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _educationtypereligious = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _educationtypeother = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _educationtypeotherdesc = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _vocationaltrainingavailable = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _percentchildrennotinschool = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _percentchildrencompletedprimaryschool = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _percentyouthcompletedsecondaryschool = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _avgfamilymonthlyincome = New Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
        _avgfamilymonthlyincomeinusdollars = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _primaryoccupationherding = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _primaryoccupationdaylabor = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _primaryoccupationdomestic = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _primaryoccupationfactory = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _primaryoccupationfishing = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _primaryoccupationgovernment = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _primaryoccupationstreetvending = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _primaryoccupationfarming = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _primaryoccupationtrading = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _primaryoccupationplantation = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _primaryoccupationporter = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _primaryoccupationother = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _primaryoccupationotherdesc = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _avghoursperweek = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _unemploymentrate = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _localtraditions = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _holidays = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _primaryethnicgroups = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _primarylanguages = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _familystructurepartriarchal = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _familystructurematriarchal = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _familystructurefamilydisintegration = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _familystructuresingleparent = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _familystructureextendedfamily = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _familystructurechildheaded = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _familystructureother = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _familystructureotherdesc = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _socialissuesalcoholabuse = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissueschildabuse = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissueschildlabor = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissueschildprostitution = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissueschildtrafficking = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissueschildheadedhouseholds = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissuesdrugabuse = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissuesforcedmarriage = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissuesgirlchilddiscrimination = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissueshighdivorce = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissuesorphans = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissuesrefugees = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissuessingleparentfamilies = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissuestrauma = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissueswar = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissuesother = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _socialissuesotherdesc = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _legalprotectionnotaware = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _legalprotectionawarenotenforced = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _legalprotectionawareenforced = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _childlaborregularlyinlaborpool = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _childlaborrsometimesinlaborpool = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _childlabornotinlaborpool = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _childcarewhenparentabsentadoption = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _childcarewhenparentabsentextendedfamily = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _childcarewhenparentabsentfostercare = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _childcarewhenparentabsentinstitution = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _childcarewhenparentabsentnocare = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _childcarewhenparentabsentother = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _childcarewhenparentabsentotherdesc = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _localadoptionaccepted = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _foreignadoptionlegal = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _highesteducationavailableotherseparator = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _educationtypeotherseparator = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _primaryoccupationotherseparator = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _familystructureotherseparator = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _socialissuesotherseparator = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New Guid("27a61e8a-fe9b-4c12-be67-9c8fdc0e9e04")
        MyBase.DataFormInstanceId = New Guid("5d8256e5-bbc9-4b3d-8b23-123b4c4bfe44")
        MyBase.RecordType = "Child Project Extension"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildProject.Community2.ViewForm.html"

        '
        '_id
        '
        _id.Name = "ID"
        _id.Caption = "ID"
        _id.Visible = False
        _id.DBReadOnly = True
        Me.Fields.Add(_id)
        '
        '_highesteducationavailablecode
        '
        _highesteducationavailablecode.Name = "HIGHESTEDUCATIONAVAILABLECODE"
        _highesteducationavailablecode.Caption = "Higest education available in local community"
        _highesteducationavailablecode.DBReadOnly = True
        _highesteducationavailablecode.MaxLength = 100
        Me.Fields.Add(_highesteducationavailablecode)
        '
        '_highesteducationavailablecodeid
        '
        _highesteducationavailablecodeid.Name = "HIGHESTEDUCATIONAVAILABLECODEID"
        _highesteducationavailablecodeid.Caption = "Higest education available in local community id"
        _highesteducationavailablecodeid.DBReadOnly = True
        Me.Fields.Add(_highesteducationavailablecodeid)
        '
        '_highesteducationavailableother
        '
        _highesteducationavailableother.Name = "HIGHESTEDUCATIONAVAILABLEOTHER"
        _highesteducationavailableother.Caption = "other"
        _highesteducationavailableother.DBReadOnly = True
        _highesteducationavailableother.MaxLength = 50
        Me.Fields.Add(_highesteducationavailableother)
        '
        '_educationsystemdivisions
        '
        _educationsystemdivisions.Name = "EDUCATIONSYSTEMDIVISIONS"
        _educationsystemdivisions.Caption = "Education system divisions"
        _educationsystemdivisions.DBReadOnly = True
        _educationsystemdivisions.MaxLength = 200
        _educationsystemdivisions.MultiLine = True
        Me.Fields.Add(_educationsystemdivisions)
        '
        '_educationtypepublic
        '
        _educationtypepublic.Name = "EDUCATIONTYPEPUBLIC"
        _educationtypepublic.Caption = "Public"
        _educationtypepublic.DBReadOnly = True
        Me.Fields.Add(_educationtypepublic)
        '
        '_educationtypeprivate
        '
        _educationtypeprivate.Name = "EDUCATIONTYPEPRIVATE"
        _educationtypeprivate.Caption = "Private"
        _educationtypeprivate.DBReadOnly = True
        Me.Fields.Add(_educationtypeprivate)
        '
        '_educationtypereligious
        '
        _educationtypereligious.Name = "EDUCATIONTYPERELIGIOUS"
        _educationtypereligious.Caption = "Religious"
        _educationtypereligious.DBReadOnly = True
        Me.Fields.Add(_educationtypereligious)
        '
        '_educationtypeother
        '
        _educationtypeother.Name = "EDUCATIONTYPEOTHER"
        _educationtypeother.Caption = "Other"
        _educationtypeother.DBReadOnly = True
        Me.Fields.Add(_educationtypeother)
        '
        '_educationtypeotherdesc
        '
        _educationtypeotherdesc.Name = "EDUCATIONTYPEOTHERDESC"
        _educationtypeotherdesc.Caption = "Otherdesc"
        _educationtypeotherdesc.DBReadOnly = True
        _educationtypeotherdesc.MaxLength = 50
        Me.Fields.Add(_educationtypeotherdesc)
        '
        '_vocationaltrainingavailable
        '
        _vocationaltrainingavailable.Name = "VOCATIONALTRAININGAVAILABLE"
        _vocationaltrainingavailable.Caption = "Types of vocational training available"
        _vocationaltrainingavailable.DBReadOnly = True
        _vocationaltrainingavailable.MaxLength = 200
        _vocationaltrainingavailable.MultiLine = True
        Me.Fields.Add(_vocationaltrainingavailable)
        '
        '_percentchildrennotinschool
        '
        _percentchildrennotinschool.Name = "PERCENTCHILDRENNOTINSCHOOL"
        _percentchildrennotinschool.Caption = "Percentage of children of school age who are not in school"
        _percentchildrennotinschool.DBReadOnly = True
        Me.Fields.Add(_percentchildrennotinschool)
        '
        '_percentchildrencompletedprimaryschool
        '
        _percentchildrencompletedprimaryschool.Name = "PERCENTCHILDRENCOMPLETEDPRIMARYSCHOOL"
        _percentchildrencompletedprimaryschool.Caption = "Percentage of children who have completed primary school"
        _percentchildrencompletedprimaryschool.DBReadOnly = True
        Me.Fields.Add(_percentchildrencompletedprimaryschool)
        '
        '_percentyouthcompletedsecondaryschool
        '
        _percentyouthcompletedsecondaryschool.Name = "PERCENTYOUTHCOMPLETEDSECONDARYSCHOOL"
        _percentyouthcompletedsecondaryschool.Caption = "Percentage of youth who have completed secondary school"
        _percentyouthcompletedsecondaryschool.DBReadOnly = True
        Me.Fields.Add(_percentyouthcompletedsecondaryschool)
        '
        '_avgfamilymonthlyincome
        '
        _avgfamilymonthlyincome.Name = "AVGFAMILYMONTHLYINCOME"
        _avgfamilymonthlyincome.Caption = "Local average family monthly income"
        _avgfamilymonthlyincome.DBReadOnly = True
        _avgfamilymonthlyincome.Precision = 8
        _avgfamilymonthlyincome.Scale = 2
        Me.Fields.Add(_avgfamilymonthlyincome)
        '
        '_avgfamilymonthlyincomeinusdollars
        '
        _avgfamilymonthlyincomeinusdollars.Name = "AVGFAMILYMONTHLYINCOMEINUSDOLLARS"
        _avgfamilymonthlyincomeinusdollars.Caption = "US average family month income"
        _avgfamilymonthlyincomeinusdollars.DBReadOnly = True
        Me.Fields.Add(_avgfamilymonthlyincomeinusdollars)
        '
        '_primaryoccupationherding
        '
        _primaryoccupationherding.Name = "PRIMARYOCCUPATIONHERDING"
        _primaryoccupationherding.Caption = "Animal herding"
        _primaryoccupationherding.DBReadOnly = True
        Me.Fields.Add(_primaryoccupationherding)
        '
        '_primaryoccupationdaylabor
        '
        _primaryoccupationdaylabor.Name = "PRIMARYOCCUPATIONDAYLABOR"
        _primaryoccupationdaylabor.Caption = "Day labor"
        _primaryoccupationdaylabor.DBReadOnly = True
        Me.Fields.Add(_primaryoccupationdaylabor)
        '
        '_primaryoccupationdomestic
        '
        _primaryoccupationdomestic.Name = "PRIMARYOCCUPATIONDOMESTIC"
        _primaryoccupationdomestic.Caption = "Domestic Services"
        _primaryoccupationdomestic.DBReadOnly = True
        Me.Fields.Add(_primaryoccupationdomestic)
        '
        '_primaryoccupationfactory
        '
        _primaryoccupationfactory.Name = "PRIMARYOCCUPATIONFACTORY"
        _primaryoccupationfactory.Caption = "Factory work"
        _primaryoccupationfactory.DBReadOnly = True
        Me.Fields.Add(_primaryoccupationfactory)
        '
        '_primaryoccupationfishing
        '
        _primaryoccupationfishing.Name = "PRIMARYOCCUPATIONFISHING"
        _primaryoccupationfishing.Caption = "Fishing"
        _primaryoccupationfishing.DBReadOnly = True
        Me.Fields.Add(_primaryoccupationfishing)
        '
        '_primaryoccupationgovernment
        '
        _primaryoccupationgovernment.Name = "PRIMARYOCCUPATIONGOVERNMENT"
        _primaryoccupationgovernment.Caption = "Government worker"
        _primaryoccupationgovernment.DBReadOnly = True
        Me.Fields.Add(_primaryoccupationgovernment)
        '
        '_primaryoccupationstreetvending
        '
        _primaryoccupationstreetvending.Name = "PRIMARYOCCUPATIONSTREETVENDING"
        _primaryoccupationstreetvending.Caption = "Street vending"
        _primaryoccupationstreetvending.DBReadOnly = True
        Me.Fields.Add(_primaryoccupationstreetvending)
        '
        '_primaryoccupationfarming
        '
        _primaryoccupationfarming.Name = "PRIMARYOCCUPATIONFARMING"
        _primaryoccupationfarming.Caption = "Subsistence farming"
        _primaryoccupationfarming.DBReadOnly = True
        Me.Fields.Add(_primaryoccupationfarming)
        '
        '_primaryoccupationtrading
        '
        _primaryoccupationtrading.Name = "PRIMARYOCCUPATIONTRADING"
        _primaryoccupationtrading.Caption = "Petty or market trading"
        _primaryoccupationtrading.DBReadOnly = True
        Me.Fields.Add(_primaryoccupationtrading)
        '
        '_primaryoccupationplantation
        '
        _primaryoccupationplantation.Name = "PRIMARYOCCUPATIONPLANTATION"
        _primaryoccupationplantation.Caption = "Plantation work"
        _primaryoccupationplantation.DBReadOnly = True
        Me.Fields.Add(_primaryoccupationplantation)
        '
        '_primaryoccupationporter
        '
        _primaryoccupationporter.Name = "PRIMARYOCCUPATIONPORTER"
        _primaryoccupationporter.Caption = "Porter or Coolie"
        _primaryoccupationporter.DBReadOnly = True
        Me.Fields.Add(_primaryoccupationporter)
        '
        '_primaryoccupationother
        '
        _primaryoccupationother.Name = "PRIMARYOCCUPATIONOTHER"
        _primaryoccupationother.Caption = "Other"
        _primaryoccupationother.DBReadOnly = True
        Me.Fields.Add(_primaryoccupationother)
        '
        '_primaryoccupationotherdesc
        '
        _primaryoccupationotherdesc.Name = "PRIMARYOCCUPATIONOTHERDESC"
        _primaryoccupationotherdesc.Caption = "OtherDesc"
        _primaryoccupationotherdesc.DBReadOnly = True
        _primaryoccupationotherdesc.MaxLength = 50
        Me.Fields.Add(_primaryoccupationotherdesc)
        '
        '_avghoursperweek
        '
        _avghoursperweek.Name = "AVGHOURSPERWEEK"
        _avghoursperweek.Caption = "Average number of hours adults work per week"
        _avghoursperweek.DBReadOnly = True
        Me.Fields.Add(_avghoursperweek)
        '
        '_unemploymentrate
        '
        _unemploymentrate.Name = "UNEMPLOYMENTRATE"
        _unemploymentrate.Caption = "Unemployment rate"
        _unemploymentrate.DBReadOnly = True
        Me.Fields.Add(_unemploymentrate)
        '
        '_localtraditions
        '
        _localtraditions.Name = "LOCALTRADITIONS"
        _localtraditions.Caption = "Local traditions, rituals and customs"
        _localtraditions.DBReadOnly = True
        _localtraditions.MaxLength = 1000
        _localtraditions.MultiLine = True
        Me.Fields.Add(_localtraditions)
        '
        '_holidays
        '
        _holidays.Name = "HOLIDAYS"
        _holidays.Caption = "Community or local reglious holidays"
        _holidays.DBReadOnly = True
        _holidays.MaxLength = 200
        _holidays.MultiLine = True
        Me.Fields.Add(_holidays)
        '
        '_primaryethnicgroups
        '
        _primaryethnicgroups.Name = "PRIMARYETHNICGROUPS"
        _primaryethnicgroups.Caption = "Primary ethnic group(s)"
        _primaryethnicgroups.DBReadOnly = True
        _primaryethnicgroups.MaxLength = 50
        Me.Fields.Add(_primaryethnicgroups)
        '
        '_primarylanguages
        '
        _primarylanguages.Name = "PRIMARYLANGUAGES"
        _primarylanguages.Caption = "Primary language(s)"
        _primarylanguages.DBReadOnly = True
        _primarylanguages.MaxLength = 50
        Me.Fields.Add(_primarylanguages)
        '
        '_familystructurepartriarchal
        '
        _familystructurepartriarchal.Name = "FAMILYSTRUCTUREPARTRIARCHAL"
        _familystructurepartriarchal.Caption = "Patriarchal"
        _familystructurepartriarchal.DBReadOnly = True
        Me.Fields.Add(_familystructurepartriarchal)
        '
        '_familystructurematriarchal
        '
        _familystructurematriarchal.Name = "FAMILYSTRUCTUREMATRIARCHAL"
        _familystructurematriarchal.Caption = "Matriarchal"
        _familystructurematriarchal.DBReadOnly = True
        Me.Fields.Add(_familystructurematriarchal)
        '
        '_familystructurefamilydisintegration
        '
        _familystructurefamilydisintegration.Name = "FAMILYSTRUCTUREFAMILYDISINTEGRATION"
        _familystructurefamilydisintegration.Caption = "Family disintegration"
        _familystructurefamilydisintegration.DBReadOnly = True
        Me.Fields.Add(_familystructurefamilydisintegration)
        '
        '_familystructuresingleparent
        '
        _familystructuresingleparent.Name = "FAMILYSTRUCTURESINGLEPARENT"
        _familystructuresingleparent.Caption = "Single parent"
        _familystructuresingleparent.DBReadOnly = True
        Me.Fields.Add(_familystructuresingleparent)
        '
        '_familystructureextendedfamily
        '
        _familystructureextendedfamily.Name = "FAMILYSTRUCTUREEXTENDEDFAMILY"
        _familystructureextendedfamily.Caption = "Extended family structure"
        _familystructureextendedfamily.DBReadOnly = True
        Me.Fields.Add(_familystructureextendedfamily)
        '
        '_familystructurechildheaded
        '
        _familystructurechildheaded.Name = "FAMILYSTRUCTURECHILDHEADED"
        _familystructurechildheaded.Caption = "Child-headed households"
        _familystructurechildheaded.DBReadOnly = True
        Me.Fields.Add(_familystructurechildheaded)
        '
        '_familystructureother
        '
        _familystructureother.Name = "FAMILYSTRUCTUREOTHER"
        _familystructureother.Caption = "Other"
        _familystructureother.DBReadOnly = True
        Me.Fields.Add(_familystructureother)
        '
        '_familystructureotherdesc
        '
        _familystructureotherdesc.Name = "FAMILYSTRUCTUREOTHERDESC"
        _familystructureotherdesc.Caption = "Family structure other description"
        _familystructureotherdesc.DBReadOnly = True
        _familystructureotherdesc.MaxLength = 50
        Me.Fields.Add(_familystructureotherdesc)
        '
        '_socialissuesalcoholabuse
        '
        _socialissuesalcoholabuse.Name = "SOCIALISSUESALCOHOLABUSE"
        _socialissuesalcoholabuse.Caption = "Alcohol abuse"
        _socialissuesalcoholabuse.DBReadOnly = True
        Me.Fields.Add(_socialissuesalcoholabuse)
        '
        '_socialissueschildabuse
        '
        _socialissueschildabuse.Name = "SOCIALISSUESCHILDABUSE"
        _socialissueschildabuse.Caption = "Child abuse/dometic violence"
        _socialissueschildabuse.DBReadOnly = True
        Me.Fields.Add(_socialissueschildabuse)
        '
        '_socialissueschildlabor
        '
        _socialissueschildlabor.Name = "SOCIALISSUESCHILDLABOR"
        _socialissueschildlabor.Caption = "Child labor"
        _socialissueschildlabor.DBReadOnly = True
        Me.Fields.Add(_socialissueschildlabor)
        '
        '_socialissueschildprostitution
        '
        _socialissueschildprostitution.Name = "SOCIALISSUESCHILDPROSTITUTION"
        _socialissueschildprostitution.Caption = "Child prostitution"
        _socialissueschildprostitution.DBReadOnly = True
        Me.Fields.Add(_socialissueschildprostitution)
        '
        '_socialissueschildtrafficking
        '
        _socialissueschildtrafficking.Name = "SOCIALISSUESCHILDTRAFFICKING"
        _socialissueschildtrafficking.Caption = "Child trafficking"
        _socialissueschildtrafficking.DBReadOnly = True
        Me.Fields.Add(_socialissueschildtrafficking)
        '
        '_socialissueschildheadedhouseholds
        '
        _socialissueschildheadedhouseholds.Name = "SOCIALISSUESCHILDHEADEDHOUSEHOLDS"
        _socialissueschildheadedhouseholds.Caption = "Child-headed households"
        _socialissueschildheadedhouseholds.DBReadOnly = True
        Me.Fields.Add(_socialissueschildheadedhouseholds)
        '
        '_socialissuesdrugabuse
        '
        _socialissuesdrugabuse.Name = "SOCIALISSUESDRUGABUSE"
        _socialissuesdrugabuse.Caption = "Drug abuse"
        _socialissuesdrugabuse.DBReadOnly = True
        Me.Fields.Add(_socialissuesdrugabuse)
        '
        '_socialissuesforcedmarriage
        '
        _socialissuesforcedmarriage.Name = "SOCIALISSUESFORCEDMARRIAGE"
        _socialissuesforcedmarriage.Caption = "Forced/arranged marriage"
        _socialissuesforcedmarriage.DBReadOnly = True
        Me.Fields.Add(_socialissuesforcedmarriage)
        '
        '_socialissuesgirlchilddiscrimination
        '
        _socialissuesgirlchilddiscrimination.Name = "SOCIALISSUESGIRLCHILDDISCRIMINATION"
        _socialissuesgirlchilddiscrimination.Caption = "Girl-child discrimination"
        _socialissuesgirlchilddiscrimination.DBReadOnly = True
        Me.Fields.Add(_socialissuesgirlchilddiscrimination)
        '
        '_socialissueshighdivorce
        '
        _socialissueshighdivorce.Name = "SOCIALISSUESHIGHDIVORCE"
        _socialissueshighdivorce.Caption = "High divorce"
        _socialissueshighdivorce.DBReadOnly = True
        Me.Fields.Add(_socialissueshighdivorce)
        '
        '_socialissuesorphans
        '
        _socialissuesorphans.Name = "SOCIALISSUESORPHANS"
        _socialissuesorphans.Caption = "Oprhans"
        _socialissuesorphans.DBReadOnly = True
        Me.Fields.Add(_socialissuesorphans)
        '
        '_socialissuesrefugees
        '
        _socialissuesrefugees.Name = "SOCIALISSUESREFUGEES"
        _socialissuesrefugees.Caption = "Refugees"
        _socialissuesrefugees.DBReadOnly = True
        Me.Fields.Add(_socialissuesrefugees)
        '
        '_socialissuessingleparentfamilies
        '
        _socialissuessingleparentfamilies.Name = "SOCIALISSUESSINGLEPARENTFAMILIES"
        _socialissuessingleparentfamilies.Caption = "Single-parent families"
        _socialissuessingleparentfamilies.DBReadOnly = True
        Me.Fields.Add(_socialissuessingleparentfamilies)
        '
        '_socialissuestrauma
        '
        _socialissuestrauma.Name = "SOCIALISSUESTRAUMA"
        _socialissuestrauma.Caption = "Trauma or Post traumatic stree disorder"
        _socialissuestrauma.DBReadOnly = True
        Me.Fields.Add(_socialissuestrauma)
        '
        '_socialissueswar
        '
        _socialissueswar.Name = "SOCIALISSUESWAR"
        _socialissueswar.Caption = "War or conflict"
        _socialissueswar.DBReadOnly = True
        Me.Fields.Add(_socialissueswar)
        '
        '_socialissuesother
        '
        _socialissuesother.Name = "SOCIALISSUESOTHER"
        _socialissuesother.Caption = "Other"
        _socialissuesother.DBReadOnly = True
        Me.Fields.Add(_socialissuesother)
        '
        '_socialissuesotherdesc
        '
        _socialissuesotherdesc.Name = "SOCIALISSUESOTHERDESC"
        _socialissuesotherdesc.Caption = "Social issues other description"
        _socialissuesotherdesc.DBReadOnly = True
        _socialissuesotherdesc.MaxLength = 50
        Me.Fields.Add(_socialissuesotherdesc)
        '
        '_legalprotectionnotaware
        '
        _legalprotectionnotaware.Name = "LEGALPROTECTIONNOTAWARE"
        _legalprotectionnotaware.Caption = "Community is unaware of the Convention on the Rights of the Child. There are no local laws to protect children."
        _legalprotectionnotaware.DBReadOnly = True
        Me.Fields.Add(_legalprotectionnotaware)
        '
        '_legalprotectionawarenotenforced
        '
        _legalprotectionawarenotenforced.Name = "LEGALPROTECTIONAWARENOTENFORCED"
        _legalprotectionawarenotenforced.Caption = "Community is aware of the Convention on the Rights of the Child, but it is not enforced. There are local laws to protect children, but they are not enforced."
        _legalprotectionawarenotenforced.DBReadOnly = True
        Me.Fields.Add(_legalprotectionawarenotenforced)
        '
        '_legalprotectionawareenforced
        '
        _legalprotectionawareenforced.Name = "LEGALPROTECTIONAWAREENFORCED"
        _legalprotectionawareenforced.Caption = "Community is aware of the Covention on the Rights of the Child and effort is made to educate and post information on this topic. There are local laws to protect children and they are enforced."
        _legalprotectionawareenforced.DBReadOnly = True
        Me.Fields.Add(_legalprotectionawareenforced)
        '
        '_childlaborregularlyinlaborpool
        '
        _childlaborregularlyinlaborpool.Name = "CHILDLABORREGULARLYINLABORPOOL"
        _childlaborregularlyinlaborpool.Caption = "Children regularly participate in the labor pool and in dangerous tasks, such as farming, factory work, and exposure to hazardous materials."
        _childlaborregularlyinlaborpool.DBReadOnly = True
        Me.Fields.Add(_childlaborregularlyinlaborpool)
        '
        '_childlaborrsometimesinlaborpool
        '
        _childlaborrsometimesinlaborpool.Name = "CHILDLABORRSOMETIMESINLABORPOOL"
        _childlaborrsometimesinlaborpool.Caption = "Children sometimes participate in the labor pool and in dangerous tasks, but do have the opportunity for education."
        _childlaborrsometimesinlaborpool.DBReadOnly = True
        Me.Fields.Add(_childlaborrsometimesinlaborpool)
        '
        '_childlabornotinlaborpool
        '
        _childlabornotinlaborpool.Name = "CHILDLABORNOTINLABORPOOL"
        _childlabornotinlaborpool.Caption = "Children do not participate in the labor pool.  Education for children is  highly encouraged and supported."
        _childlabornotinlaborpool.DBReadOnly = True
        Me.Fields.Add(_childlabornotinlaborpool)
        '
        '_childcarewhenparentabsentadoption
        '
        _childcarewhenparentabsentadoption.Name = "CHILDCAREWHENPARENTABSENTADOPTION"
        _childcarewhenparentabsentadoption.Caption = "Adoption"
        _childcarewhenparentabsentadoption.DBReadOnly = True
        Me.Fields.Add(_childcarewhenparentabsentadoption)
        '
        '_childcarewhenparentabsentextendedfamily
        '
        _childcarewhenparentabsentextendedfamily.Name = "CHILDCAREWHENPARENTABSENTEXTENDEDFAMILY"
        _childcarewhenparentabsentextendedfamily.Caption = "Extended family"
        _childcarewhenparentabsentextendedfamily.DBReadOnly = True
        Me.Fields.Add(_childcarewhenparentabsentextendedfamily)
        '
        '_childcarewhenparentabsentfostercare
        '
        _childcarewhenparentabsentfostercare.Name = "CHILDCAREWHENPARENTABSENTFOSTERCARE"
        _childcarewhenparentabsentfostercare.Caption = "Foster care"
        _childcarewhenparentabsentfostercare.DBReadOnly = True
        Me.Fields.Add(_childcarewhenparentabsentfostercare)
        '
        '_childcarewhenparentabsentinstitution
        '
        _childcarewhenparentabsentinstitution.Name = "CHILDCAREWHENPARENTABSENTINSTITUTION"
        _childcarewhenparentabsentinstitution.Caption = "Institution"
        _childcarewhenparentabsentinstitution.DBReadOnly = True
        Me.Fields.Add(_childcarewhenparentabsentinstitution)
        '
        '_childcarewhenparentabsentnocare
        '
        _childcarewhenparentabsentnocare.Name = "CHILDCAREWHENPARENTABSENTNOCARE"
        _childcarewhenparentabsentnocare.Caption = "No care available"
        _childcarewhenparentabsentnocare.DBReadOnly = True
        Me.Fields.Add(_childcarewhenparentabsentnocare)
        '
        '_childcarewhenparentabsentother
        '
        _childcarewhenparentabsentother.Name = "CHILDCAREWHENPARENTABSENTOTHER"
        _childcarewhenparentabsentother.Caption = "Other"
        _childcarewhenparentabsentother.DBReadOnly = True
        Me.Fields.Add(_childcarewhenparentabsentother)
        '
        '_childcarewhenparentabsentotherdesc
        '
        _childcarewhenparentabsentotherdesc.Name = "CHILDCAREWHENPARENTABSENTOTHERDESC"
        _childcarewhenparentabsentotherdesc.Caption = "Child care when parent absent other description"
        _childcarewhenparentabsentotherdesc.DBReadOnly = True
        _childcarewhenparentabsentotherdesc.MaxLength = 50
        Me.Fields.Add(_childcarewhenparentabsentotherdesc)
        '
        '_localadoptionaccepted
        '
        _localadoptionaccepted.Name = "LOCALADOPTIONACCEPTED"
        _localadoptionaccepted.Caption = "Is local adoption accepted?"
        _localadoptionaccepted.DBReadOnly = True
        _localadoptionaccepted.MaxLength = 20
        Me.Fields.Add(_localadoptionaccepted)
        '
        '_foreignadoptionlegal
        '
        _foreignadoptionlegal.Name = "FOREIGNADOPTIONLEGAL"
        _foreignadoptionlegal.Caption = "Is foreign adoption legal?"
        _foreignadoptionlegal.DBReadOnly = True
        _foreignadoptionlegal.MaxLength = 20
        Me.Fields.Add(_foreignadoptionlegal)
        '
        '_highesteducationavailableotherseparator
        '
        _highesteducationavailableotherseparator.Name = "HIGHESTEDUCATIONAVAILABLEOTHERSEPARATOR"
        _highesteducationavailableotherseparator.Caption = "HIGHESTEDUCATIONAVAILABLEOTHERSEPARATOR"
        _highesteducationavailableotherseparator.DBReadOnly = True
        _highesteducationavailableotherseparator.MaxLength = 1
        Me.Fields.Add(_highesteducationavailableotherseparator)
        '
        '_educationtypeotherseparator
        '
        _educationtypeotherseparator.Name = "EDUCATIONTYPEOTHERSEPARATOR"
        _educationtypeotherseparator.Caption = "EDUCATIONTYPEOTHERSEPARATOR"
        _educationtypeotherseparator.DBReadOnly = True
        _educationtypeotherseparator.MaxLength = 1
        Me.Fields.Add(_educationtypeotherseparator)
        '
        '_primaryoccupationotherseparator
        '
        _primaryoccupationotherseparator.Name = "PRIMARYOCCUPATIONOTHERSEPARATOR"
        _primaryoccupationotherseparator.Caption = "PRIMARYOCCUPATIONOTHERSEPARATOR"
        _primaryoccupationotherseparator.DBReadOnly = True
        _primaryoccupationotherseparator.MaxLength = 1
        Me.Fields.Add(_primaryoccupationotherseparator)
        '
        '_familystructureotherseparator
        '
        _familystructureotherseparator.Name = "FAMILYSTRUCTUREOTHERSEPARATOR"
        _familystructureotherseparator.Caption = "FAMILYSTRUCTUREOTHERSEPARATOR"
        _familystructureotherseparator.DBReadOnly = True
        _familystructureotherseparator.MaxLength = 1
        Me.Fields.Add(_familystructureotherseparator)
        '
        '_socialissuesotherseparator
        '
        _socialissuesotherseparator.Name = "SOCIALISSUESOTHERSEPARATOR"
        _socialissuesotherseparator.Caption = "SOCIALISSUESOTHERSEPARATOR"
        _socialissuesotherseparator.DBReadOnly = True
        _socialissuesotherseparator.MaxLength = 1
        Me.Fields.Add(_socialissuesotherseparator)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _id
        End Get
    End Property
    
    ''' <summary>
    ''' Higest education available in local community
    ''' </summary>
    <System.ComponentModel.Description("Higest education available in local community")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HIGHESTEDUCATIONAVAILABLECODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _highesteducationavailablecode
        End Get
    End Property
    
    ''' <summary>
    ''' Higest education available in local community id
    ''' </summary>
    <System.ComponentModel.Description("Higest education available in local community id")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HIGHESTEDUCATIONAVAILABLECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _highesteducationavailablecodeid
        End Get
    End Property
    
    ''' <summary>
    ''' other
    ''' </summary>
    <System.ComponentModel.Description("other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HIGHESTEDUCATIONAVAILABLEOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _highesteducationavailableother
        End Get
    End Property
    
    ''' <summary>
    ''' Education system divisions
    ''' </summary>
    <System.ComponentModel.Description("Education system divisions")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [EDUCATIONSYSTEMDIVISIONS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _educationsystemdivisions
        End Get
    End Property
    
    ''' <summary>
    ''' Public
    ''' </summary>
    <System.ComponentModel.Description("Public")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [EDUCATIONTYPEPUBLIC]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _educationtypepublic
        End Get
    End Property
    
    ''' <summary>
    ''' Private
    ''' </summary>
    <System.ComponentModel.Description("Private")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [EDUCATIONTYPEPRIVATE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _educationtypeprivate
        End Get
    End Property
    
    ''' <summary>
    ''' Religious
    ''' </summary>
    <System.ComponentModel.Description("Religious")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [EDUCATIONTYPERELIGIOUS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _educationtypereligious
        End Get
    End Property
    
    ''' <summary>
    ''' Other
    ''' </summary>
    <System.ComponentModel.Description("Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [EDUCATIONTYPEOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _educationtypeother
        End Get
    End Property
    
    ''' <summary>
    ''' Otherdesc
    ''' </summary>
    <System.ComponentModel.Description("Otherdesc")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [EDUCATIONTYPEOTHERDESC]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _educationtypeotherdesc
        End Get
    End Property
    
    ''' <summary>
    ''' Types of vocational training available
    ''' </summary>
    <System.ComponentModel.Description("Types of vocational training available")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [VOCATIONALTRAININGAVAILABLE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _vocationaltrainingavailable
        End Get
    End Property
    
    ''' <summary>
    ''' Percentage of children of school age who are not in school
    ''' </summary>
    <System.ComponentModel.Description("Percentage of children of school age who are not in school")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PERCENTCHILDRENNOTINSCHOOL]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _percentchildrennotinschool
        End Get
    End Property
    
    ''' <summary>
    ''' Percentage of children who have completed primary school
    ''' </summary>
    <System.ComponentModel.Description("Percentage of children who have completed primary school")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PERCENTCHILDRENCOMPLETEDPRIMARYSCHOOL]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _percentchildrencompletedprimaryschool
        End Get
    End Property
    
    ''' <summary>
    ''' Percentage of youth who have completed secondary school
    ''' </summary>
    <System.ComponentModel.Description("Percentage of youth who have completed secondary school")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PERCENTYOUTHCOMPLETEDSECONDARYSCHOOL]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _percentyouthcompletedsecondaryschool
        End Get
    End Property
    
    ''' <summary>
    ''' Local average family monthly income
    ''' </summary>
    <System.ComponentModel.Description("Local average family monthly income")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [AVGFAMILYMONTHLYINCOME]() As Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
        Get
            Return _avgfamilymonthlyincome
        End Get
    End Property
    
    ''' <summary>
    ''' US average family month income
    ''' </summary>
    <System.ComponentModel.Description("US average family month income")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [AVGFAMILYMONTHLYINCOMEINUSDOLLARS]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _avgfamilymonthlyincomeinusdollars
        End Get
    End Property
    
    ''' <summary>
    ''' Animal herding
    ''' </summary>
    <System.ComponentModel.Description("Animal herding")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYOCCUPATIONHERDING]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _primaryoccupationherding
        End Get
    End Property
    
    ''' <summary>
    ''' Day labor
    ''' </summary>
    <System.ComponentModel.Description("Day labor")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYOCCUPATIONDAYLABOR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _primaryoccupationdaylabor
        End Get
    End Property
    
    ''' <summary>
    ''' Domestic Services
    ''' </summary>
    <System.ComponentModel.Description("Domestic Services")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYOCCUPATIONDOMESTIC]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _primaryoccupationdomestic
        End Get
    End Property
    
    ''' <summary>
    ''' Factory work
    ''' </summary>
    <System.ComponentModel.Description("Factory work")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYOCCUPATIONFACTORY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _primaryoccupationfactory
        End Get
    End Property
    
    ''' <summary>
    ''' Fishing
    ''' </summary>
    <System.ComponentModel.Description("Fishing")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYOCCUPATIONFISHING]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _primaryoccupationfishing
        End Get
    End Property
    
    ''' <summary>
    ''' Government worker
    ''' </summary>
    <System.ComponentModel.Description("Government worker")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYOCCUPATIONGOVERNMENT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _primaryoccupationgovernment
        End Get
    End Property
    
    ''' <summary>
    ''' Street vending
    ''' </summary>
    <System.ComponentModel.Description("Street vending")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYOCCUPATIONSTREETVENDING]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _primaryoccupationstreetvending
        End Get
    End Property
    
    ''' <summary>
    ''' Subsistence farming
    ''' </summary>
    <System.ComponentModel.Description("Subsistence farming")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYOCCUPATIONFARMING]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _primaryoccupationfarming
        End Get
    End Property
    
    ''' <summary>
    ''' Petty or market trading
    ''' </summary>
    <System.ComponentModel.Description("Petty or market trading")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYOCCUPATIONTRADING]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _primaryoccupationtrading
        End Get
    End Property
    
    ''' <summary>
    ''' Plantation work
    ''' </summary>
    <System.ComponentModel.Description("Plantation work")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYOCCUPATIONPLANTATION]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _primaryoccupationplantation
        End Get
    End Property
    
    ''' <summary>
    ''' Porter or Coolie
    ''' </summary>
    <System.ComponentModel.Description("Porter or Coolie")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYOCCUPATIONPORTER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _primaryoccupationporter
        End Get
    End Property
    
    ''' <summary>
    ''' Other
    ''' </summary>
    <System.ComponentModel.Description("Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYOCCUPATIONOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _primaryoccupationother
        End Get
    End Property
    
    ''' <summary>
    ''' OtherDesc
    ''' </summary>
    <System.ComponentModel.Description("OtherDesc")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYOCCUPATIONOTHERDESC]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _primaryoccupationotherdesc
        End Get
    End Property
    
    ''' <summary>
    ''' Average number of hours adults work per week
    ''' </summary>
    <System.ComponentModel.Description("Average number of hours adults work per week")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [AVGHOURSPERWEEK]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _avghoursperweek
        End Get
    End Property
    
    ''' <summary>
    ''' Unemployment rate
    ''' </summary>
    <System.ComponentModel.Description("Unemployment rate")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [UNEMPLOYMENTRATE]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _unemploymentrate
        End Get
    End Property
    
    ''' <summary>
    ''' Local traditions, rituals and customs
    ''' </summary>
    <System.ComponentModel.Description("Local traditions, rituals and customs")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LOCALTRADITIONS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _localtraditions
        End Get
    End Property
    
    ''' <summary>
    ''' Community or local reglious holidays
    ''' </summary>
    <System.ComponentModel.Description("Community or local reglious holidays")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HOLIDAYS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _holidays
        End Get
    End Property
    
    ''' <summary>
    ''' Primary ethnic group(s)
    ''' </summary>
    <System.ComponentModel.Description("Primary ethnic group(s)")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYETHNICGROUPS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _primaryethnicgroups
        End Get
    End Property
    
    ''' <summary>
    ''' Primary language(s)
    ''' </summary>
    <System.ComponentModel.Description("Primary language(s)")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYLANGUAGES]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _primarylanguages
        End Get
    End Property
    
    ''' <summary>
    ''' Patriarchal
    ''' </summary>
    <System.ComponentModel.Description("Patriarchal")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FAMILYSTRUCTUREPARTRIARCHAL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _familystructurepartriarchal
        End Get
    End Property
    
    ''' <summary>
    ''' Matriarchal
    ''' </summary>
    <System.ComponentModel.Description("Matriarchal")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FAMILYSTRUCTUREMATRIARCHAL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _familystructurematriarchal
        End Get
    End Property
    
    ''' <summary>
    ''' Family disintegration
    ''' </summary>
    <System.ComponentModel.Description("Family disintegration")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FAMILYSTRUCTUREFAMILYDISINTEGRATION]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _familystructurefamilydisintegration
        End Get
    End Property
    
    ''' <summary>
    ''' Single parent
    ''' </summary>
    <System.ComponentModel.Description("Single parent")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FAMILYSTRUCTURESINGLEPARENT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _familystructuresingleparent
        End Get
    End Property
    
    ''' <summary>
    ''' Extended family structure
    ''' </summary>
    <System.ComponentModel.Description("Extended family structure")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FAMILYSTRUCTUREEXTENDEDFAMILY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _familystructureextendedfamily
        End Get
    End Property
    
    ''' <summary>
    ''' Child-headed households
    ''' </summary>
    <System.ComponentModel.Description("Child-headed households")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FAMILYSTRUCTURECHILDHEADED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _familystructurechildheaded
        End Get
    End Property
    
    ''' <summary>
    ''' Other
    ''' </summary>
    <System.ComponentModel.Description("Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FAMILYSTRUCTUREOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _familystructureother
        End Get
    End Property
    
    ''' <summary>
    ''' Family structure other description
    ''' </summary>
    <System.ComponentModel.Description("Family structure other description")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FAMILYSTRUCTUREOTHERDESC]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _familystructureotherdesc
        End Get
    End Property
    
    ''' <summary>
    ''' Alcohol abuse
    ''' </summary>
    <System.ComponentModel.Description("Alcohol abuse")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESALCOHOLABUSE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissuesalcoholabuse
        End Get
    End Property
    
    ''' <summary>
    ''' Child abuse/dometic violence
    ''' </summary>
    <System.ComponentModel.Description("Child abuse/dometic violence")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESCHILDABUSE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissueschildabuse
        End Get
    End Property
    
    ''' <summary>
    ''' Child labor
    ''' </summary>
    <System.ComponentModel.Description("Child labor")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESCHILDLABOR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissueschildlabor
        End Get
    End Property
    
    ''' <summary>
    ''' Child prostitution
    ''' </summary>
    <System.ComponentModel.Description("Child prostitution")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESCHILDPROSTITUTION]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissueschildprostitution
        End Get
    End Property
    
    ''' <summary>
    ''' Child trafficking
    ''' </summary>
    <System.ComponentModel.Description("Child trafficking")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESCHILDTRAFFICKING]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissueschildtrafficking
        End Get
    End Property
    
    ''' <summary>
    ''' Child-headed households
    ''' </summary>
    <System.ComponentModel.Description("Child-headed households")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESCHILDHEADEDHOUSEHOLDS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissueschildheadedhouseholds
        End Get
    End Property
    
    ''' <summary>
    ''' Drug abuse
    ''' </summary>
    <System.ComponentModel.Description("Drug abuse")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESDRUGABUSE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissuesdrugabuse
        End Get
    End Property
    
    ''' <summary>
    ''' Forced/arranged marriage
    ''' </summary>
    <System.ComponentModel.Description("Forced/arranged marriage")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESFORCEDMARRIAGE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissuesforcedmarriage
        End Get
    End Property
    
    ''' <summary>
    ''' Girl-child discrimination
    ''' </summary>
    <System.ComponentModel.Description("Girl-child discrimination")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESGIRLCHILDDISCRIMINATION]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissuesgirlchilddiscrimination
        End Get
    End Property
    
    ''' <summary>
    ''' High divorce
    ''' </summary>
    <System.ComponentModel.Description("High divorce")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESHIGHDIVORCE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissueshighdivorce
        End Get
    End Property
    
    ''' <summary>
    ''' Oprhans
    ''' </summary>
    <System.ComponentModel.Description("Oprhans")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESORPHANS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissuesorphans
        End Get
    End Property
    
    ''' <summary>
    ''' Refugees
    ''' </summary>
    <System.ComponentModel.Description("Refugees")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESREFUGEES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissuesrefugees
        End Get
    End Property
    
    ''' <summary>
    ''' Single-parent families
    ''' </summary>
    <System.ComponentModel.Description("Single-parent families")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESSINGLEPARENTFAMILIES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissuessingleparentfamilies
        End Get
    End Property
    
    ''' <summary>
    ''' Trauma or Post traumatic stree disorder
    ''' </summary>
    <System.ComponentModel.Description("Trauma or Post traumatic stree disorder")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESTRAUMA]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissuestrauma
        End Get
    End Property
    
    ''' <summary>
    ''' War or conflict
    ''' </summary>
    <System.ComponentModel.Description("War or conflict")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESWAR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissueswar
        End Get
    End Property
    
    ''' <summary>
    ''' Other
    ''' </summary>
    <System.ComponentModel.Description("Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _socialissuesother
        End Get
    End Property
    
    ''' <summary>
    ''' Social issues other description
    ''' </summary>
    <System.ComponentModel.Description("Social issues other description")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESOTHERDESC]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _socialissuesotherdesc
        End Get
    End Property
    
    ''' <summary>
    ''' Community is unaware of the Convention on the Rights of the Child. There are no local laws to protect children.
    ''' </summary>
    <System.ComponentModel.Description("Community is unaware of the Convention on the Rights of the Child. There are no local laws to protect children.")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LEGALPROTECTIONNOTAWARE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _legalprotectionnotaware
        End Get
    End Property
    
    ''' <summary>
    ''' Community is aware of the Convention on the Rights of the Child, but it is not enforced. There are local laws to protect children, but they are not enforced.
    ''' </summary>
    <System.ComponentModel.Description("Community is aware of the Convention on the Rights of the Child, but it is not enforced. There are local laws to protect children, but they are not enforced.")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LEGALPROTECTIONAWARENOTENFORCED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _legalprotectionawarenotenforced
        End Get
    End Property
    
    ''' <summary>
    ''' Community is aware of the Covention on the Rights of the Child and effort is made to educate and post information on this topic. There are local laws to protect children and they are enforced.
    ''' </summary>
    <System.ComponentModel.Description("Community is aware of the Covention on the Rights of the Child and effort is made to educate and post information on this topic. There are local laws to protect children and they are enforced.")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LEGALPROTECTIONAWAREENFORCED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _legalprotectionawareenforced
        End Get
    End Property
    
    ''' <summary>
    ''' Children regularly participate in the labor pool and in dangerous tasks, such as farming, factory work, and exposure to hazardous materials.
    ''' </summary>
    <System.ComponentModel.Description("Children regularly participate in the labor pool and in dangerous tasks, such as farming, factory work, and exposure to hazardous materials.")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDLABORREGULARLYINLABORPOOL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _childlaborregularlyinlaborpool
        End Get
    End Property
    
    ''' <summary>
    ''' Children sometimes participate in the labor pool and in dangerous tasks, but do have the opportunity for education.
    ''' </summary>
    <System.ComponentModel.Description("Children sometimes participate in the labor pool and in dangerous tasks, but do have the opportunity for education.")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDLABORRSOMETIMESINLABORPOOL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _childlaborrsometimesinlaborpool
        End Get
    End Property
    
    ''' <summary>
    ''' Children do not participate in the labor pool.  Education for children is  highly encouraged and supported.
    ''' </summary>
    <System.ComponentModel.Description("Children do not participate in the labor pool.  Education for children is  highly encouraged and supported.")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDLABORNOTINLABORPOOL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _childlabornotinlaborpool
        End Get
    End Property
    
    ''' <summary>
    ''' Adoption
    ''' </summary>
    <System.ComponentModel.Description("Adoption")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDCAREWHENPARENTABSENTADOPTION]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _childcarewhenparentabsentadoption
        End Get
    End Property
    
    ''' <summary>
    ''' Extended family
    ''' </summary>
    <System.ComponentModel.Description("Extended family")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDCAREWHENPARENTABSENTEXTENDEDFAMILY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _childcarewhenparentabsentextendedfamily
        End Get
    End Property
    
    ''' <summary>
    ''' Foster care
    ''' </summary>
    <System.ComponentModel.Description("Foster care")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDCAREWHENPARENTABSENTFOSTERCARE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _childcarewhenparentabsentfostercare
        End Get
    End Property
    
    ''' <summary>
    ''' Institution
    ''' </summary>
    <System.ComponentModel.Description("Institution")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDCAREWHENPARENTABSENTINSTITUTION]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _childcarewhenparentabsentinstitution
        End Get
    End Property
    
    ''' <summary>
    ''' No care available
    ''' </summary>
    <System.ComponentModel.Description("No care available")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDCAREWHENPARENTABSENTNOCARE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _childcarewhenparentabsentnocare
        End Get
    End Property
    
    ''' <summary>
    ''' Other
    ''' </summary>
    <System.ComponentModel.Description("Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDCAREWHENPARENTABSENTOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _childcarewhenparentabsentother
        End Get
    End Property
    
    ''' <summary>
    ''' Child care when parent absent other description
    ''' </summary>
    <System.ComponentModel.Description("Child care when parent absent other description")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDCAREWHENPARENTABSENTOTHERDESC]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _childcarewhenparentabsentotherdesc
        End Get
    End Property
    
    ''' <summary>
    ''' Is local adoption accepted?
    ''' </summary>
    <System.ComponentModel.Description("Is local adoption accepted?")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LOCALADOPTIONACCEPTED]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _localadoptionaccepted
        End Get
    End Property
    
    ''' <summary>
    ''' Is foreign adoption legal?
    ''' </summary>
    <System.ComponentModel.Description("Is foreign adoption legal?")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FOREIGNADOPTIONLEGAL]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _foreignadoptionlegal
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HIGHESTEDUCATIONAVAILABLEOTHERSEPARATOR]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _highesteducationavailableotherseparator
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [EDUCATIONTYPEOTHERSEPARATOR]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _educationtypeotherseparator
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PRIMARYOCCUPATIONOTHERSEPARATOR]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _primaryoccupationotherseparator
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FAMILYSTRUCTUREOTHERSEPARATOR]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _familystructureotherseparator
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIALISSUESOTHERSEPARATOR]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _socialissuesotherseparator
        End Get
    End Property
    
End Class
